<?php
/**
 *
 * @category : RLTSquare
 * @Package  : RLTSquare_CustomerGroupPricing
 * @Author   : RLTSquare <support@rltsquare.com>
 * @copyright Copyright 2021 © rltsquare.com All right reserved
 * @license https://rltsquare.com/
 */

/**
 * @var \Magento\Framework\Pricing\Render\Amount $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div id="special-price-<?= /** @escapeNotVerified */ $block->getSaleableItem()->getEntityId(); ?>"></div>
<script type="text/x-magento-init">
        {
            "*": {
                "RLTSquare_CustomerGroupPricing/js/applyCustomerPrice": {
                    "requestUrl": "<?= $escaper->escapeUrl($block->getUrl("/customergrouppricing/product/getcustomerprice")) ?>",
                    "ProductId" : "<?= /** @escapeNotVerified */ $block->getSaleableItem()->getEntityId() ?>",
                    "OriginalPrice" : "<?= /** @escapeNotVerified */ $block->getDisplayValue() ?>",
                    "OriginalSymbol": "<?= /** @escapeNotVerified */ $block->getDisplayCurrencySymbol() ?>"
                }
            }
        }
</script>
